version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: wyattwalter/case-api
    docker:
      - image: circleci/buildpack-deps:stretch
orbs:
  node: circleci/node@3.0.0
workflows:
  build-image:
    jobs:
      - build-image
      - publish-image:
          requires:
            - build-image
          context:
            - DockerHub
  node-tests:
    jobs:
      - test
jobs:
  test:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run lint
          name: run eslint
      - run:
          command: yarn run test
          name: Run test suite
  build-image:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: build image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: archive the Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-image:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: publish docker image
          command: |
            echo "${DOCKER_TOKEN}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
            docker push $IMAGE_NAME:latest
