version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  build-image:
    jobs:
      - build-image
  node-tests:
    jobs:
      - test
  publish-image:
    context: GitHub Packages
    requires:
      - build-image
    jobs:
      - publish-image
jobs:
  test:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run lint
          name: run eslint
      - run:
          command: yarn run test
          name: Run test suite
  build-image:
    environment:
      IMAGE_NAME: docker.pkg.github.com/wyattwalter/case-api/case-api
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: build image
          command: docker build -t $IMAGE_NAME:latest .
  publish-image:
    environment:
      IMAGE_NAME: docker.pkg.github.com/wyattwalter/case-api/case-api
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - run:
          name: publish docker image
          command: echo "hi"
