version: 2.1
executors:
  runner:
    environment:
      IMAGE_NAME: wyattwalter/case-api
    docker:
      - image: circleci/buildpack-deps:stretch
orbs:
  node: circleci/node@3.0.0
workflows:
  build-and-test:
    jobs:
      - build-and-test
      - publish-image:
          requires:
            - build-and-test
          context:
            - DockerHub
jobs:
  build-and-test:
    executor: runner
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: build image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: yarn lint
          command: docker run --rm $IMAGE_NAME:latest lint
      - run:
          name: yarn test
          command: docker run --rm $IMAGE_NAME:latest test
      - run:
          name: archive the Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-image:
    executor: runner
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: publish docker image
          command: |
            echo "${DOCKER_TOKEN}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
            docker push $IMAGE_NAME:latest
